# Generated by Django 3.2.4 on 2021-09-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='imageurl',
            field=models.TextField(default=None, max_length=64),
        ),
    ]
