# Generated by Django 3.2.4 on 2021-09-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_websites_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='imageurl',
            field=models.TextField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
