# Generated by Django 3.2.4 on 2021-09-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_websites_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websites',
            name='imageurl',
        ),
    ]
