# Generated by Django 3.2.4 on 2021-09-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_websites_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='imageurl',
            field=models.TextField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='websites',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
