# Generated by Django 3.2.4 on 2021-09-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210914_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websites',
            name='imageurl',
        ),
    ]
